# Generated by Django 4.1.1 on 2022-09-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UAM", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        choices=[
                            ("Bellina", "Bellina"),
                            ("Sophos", "Sophos"),
                            ("Palladium", "Palladium"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="agent",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="grade",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="operating_office",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="active_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "Male"), (1, "Female")], default=0, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Employee_Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UAM.applications",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UAM.employee"
                    ),
                ),
            ],
        ),
    ]
