# Generated by Django 4.1.1 on 2022-09-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UAM", "0003_remove_employee_access_app_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="applications", name="employee_access",),
        migrations.AddField(
            model_name="employee_access",
            name="app",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="UAM.applications",
            ),
            preserve_default=False,
        ),
    ]
