# Generated by Django 4.1.1 on 2022-09-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UAM", "0004_remove_applications_employee_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="date_captured",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="applications",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
