# Generated by Django 4.1.1 on 2022-09-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UAM", "0005_applications_date_captured_applications_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applications",
            name="name",
            field=models.IntegerField(
                choices=[
                    ("", ""),
                    ("Bellina", "Bellina"),
                    ("Sophos", "Sophos"),
                    ("Palladium", "Palladium"),
                ],
                default="",
                null=True,
            ),
        ),
    ]
