# Generated by Django 4.1.1 on 2022-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UAM", "0007_alter_applications_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Access_Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorised_by", models.CharField(max_length=100)),
                ("date_authorised", models.DateField()),
                ("recommended_by", models.CharField(max_length=100)),
                ("date_recommended", models.DateField()),
                ("actioned_by", models.CharField(max_length=100)),
                ("date_actioned", models.DateField()),
            ],
        ),
    ]
